# Generated by Django 5.2.4 on 2025-08-08 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(unique=True)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('F', 'Woman'), ('NB', 'Non-binary'), ('GF', 'Genderfluid'), ('TF', 'Transfeminine'), ('TM', 'Transmasculine'), ('Q', 'Genderqueer'), ('A', 'Agender'), ('O', 'Other'), ('N', 'Prefer not to say')])),
                ('animals', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N')),
                ('role', models.CharField(choices=[('T', 'Tenant'), ('L', 'Landlord')], default='T')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'Users profiles',
                'db_table': 'user_profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
