# Generated by Django 5.2.4 on 2025-08-08 13:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=12)),
                ('haus_number', models.PositiveSmallIntegerField()),
                ('house_letter', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='user.userprofilemodel')),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='HabitationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type_housing', models.CharField(choices=[('R', 'Room'), ('A', 'Apartment'), ('H', 'Haus')])),
                ('status', models.CharField(choices=[('A', 'Actively'), ('NA', 'Not Active')], default='Actively')),
                ('number_of_rooms', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitations', to='booking.addressmodel')),
            ],
            options={
                'db_table': 'habitations',
                'unique_together': {('title', 'description', 'type_housing', 'number_of_rooms', 'status', 'address')},
            },
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.CharField(choices=[(0, 'No'), (1, 'Yes')], default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('confirmation', models.CharField(choices=[('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('awaiting', 'Awaiting')], default='awaiting')),
                ('status_order', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='user.userprofilemodel')),
                ('housing_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_detail_booking', to='booking.habitationmodel')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=300)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='booking_reviews', to='booking.bookingmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to='user.userprofilemodel')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
